clothing_items = [
    ('t-shirt', 'plain black tee', 'L', 'banana republic', 'black', 0, 15),
    ('t-shirt', 'plain black tee', 'L', 'banana republic', 'black', 0, 15),
    ('t-shirt', 'plain light blue tee', 'L', 'calvin klein', 'light blue', 0, 15),
    ('t-shirt', 'plain red tee', 'L', 'calvin klein', 'red', 0, 15),
    ('t-shirt', 'active shirt', 'L', 'puma', 'black', 0, 15),
    ('t-shirt', 'uconn rec tee', 'XL', 'gildan', 'navy blue', 5, 0),
    ('t-shirt', 'tolland soccer tee', 'M', 'tolland', 'gray', 10, 0),
    ('t-shirt', 'tolland soccer tee', 'M', 'tolland', 'gray', 10, 0),
    ('t-shirt', 'yosemite tee', 'XL', 'call your mother', 'white / pink', 0, 5),
    ('t-shirt', 'plain grayish/blue tee', 'L', 'banana republic', 'gray / blue', 0, 15),
    ('t-shirt', 'drink local CT', 'L', 'walmart', 'gray / yellow', 2, 12),
    ('t-shirt', 'acadia national park', 'L', 'eastern mountain sports', 'orange', 0, 0),
    ('t-shirt', 'wave washed billabong', 'M', 'billabong', 'green', 7, 30),
    ('t-shirt', 'death valley', 'XL', 'call your mother', 'blue', 0, 0),
    ('t-shirt', 'adidas landscape', 'L', 'adidas', 'white / blue', 3, 10),
    ('t-shirt', 'nike air', 'L', 'nike', 'black / orange', 3, 35),
    ('t-shirt', 'plain orange tee', 'L', 'banana republic', 'orange', 1, 30),
    ('t-shirt', 'never stop exploring', 'M', 'north face', 'blue', 3, 10),
    ('t-shirt', 'uconn national champs 24', 'L', 'fanatics', 'navy blue', 0, 0),
    ('t-shirt', 'uconn national champs 23', 'L', 'fanatics', 'blue', 1, 0),
    ('t-shirt', 'steelers cotton', 'L', 'fanatics', 'black', 0, 0),
    ('t-shirt', 'adidas logo tee', 'L', 'adidas', 'black', 3, 10),
    ('t-shirt', 'steelers dry fit', 'M', 'nike', 'black', 0, 6),
    ('t-shirt', 'green columbia tee', 'L', 'columbia', 'green', 1, 30),
    ('t-shirt', 'gray bear columbia', 'L', 'columbia', 'gray', 0, 15),
    ('t-shirt', 'Buc-ee\'s tee', 'L', 'Buc-ees', 'red', 0, 15),
    ('long sleeve shirt', 'blue timberland', 'L', 'timberland', 'navy', 2, 10),
    ('long sleeve shirt', 'plain red shirt', 'L', 'avalanche', 'red', 0, 0),
    ('long sleeve shirt', 'plain purple shirt', 'L', 'avalanche', 'purple', 0, 0),
    ('long sleeve shirt', 'longhorns dry fit', 'L', 'columbia', 'orange', 0, 40),
    ('long sleeve shirt', 'black dry fit workout', 'L', 'motion', 'black', 0, 0),
    ('long sleeve shirt', 'old navy sweater', 'L', 'old navy', 'tan', 3, 10),
    ('long sleeve shirt', 'gray champion large logo', 'L', 'champion', 'gray', 3, 10),
    ('long sleeve shirt', 'green dry fit workout', 'L', 'motion', 'green', 0, 0),
    ('long sleeve shirt', 'gray sleep shirt', 'L', 'primark', 'gray', 0, 0),
    ('long sleeve shirt', 'gray north face', 'L', 'north face', 'gray', 2, 0),
    ('long sleeve shirt', 'budweiser king od beers', 'L', 'pacsun', 'cream', 2, 25),
    ('long sleeve shirt', 'hofstra shirt', 'L', 'bella-canvas', 'white', 0, 40),
    ('long sleeve shirt', 'waffle sweater black', 'M', 'champs', 'black', 2, 10),
    ('long sleeve shirt', 'waffle sweater blue', 'M', 'gap', 'blue', 2, 10),
    ('long sleeve shirt', 'waffle sweater red', 'L', 'polo ralpha lauren', 'red', 2, 15),
    ('long sleeve shirt', 'floral shirt', 'L', 'champion', 'red', 2, 30),
    ('sweatshirt', 'landscape eddie bauer hoddie', 'L', 'eddie bauer', 'green', 0, 0),
    ('sweatshirt', 'uconn running hoodie', 'L', 'captivating', 'gray', 2, 0),
    ('sweatshirt', 'adp hoodie', 'L', 'gildan', 'gray', 5, 0),
    ('sweatshirt', 'blue dry fit compression hoodie', 'L', 'isaac mizrahi', 'blue', 0, 0),
    ('sweatshirt', 'teal crewneck', 'L', 'vans', 'teal', 2, 10),
    ('sweatshirt', 'uconn running quarterzip', 'L', 'colosseum', 'blue', 3, 0),
    ('sweatshirt', 'corona light hoodie', 'L', 'corona', 'light blue', 1, 25),
    ('sweatshirt', 'plain black hoodie', 'M', 'champion', 'black', 4, 0),
    ('sweatshirt', 'uconn gray hoodie', 'L', 'champion', 'gray', 6, 0),
    ('sweatshirt', 'light blue quarterzip', 'L', 'motion', 'light blue', 0, 0),
    ('sweatshirt', 'lambent quarterzip', 'L', 'north face', 'gray', 2, 0),
    ('sweatshirt', 'blue adidas crewneck', 'L', 'adidas', 'blue', 2, 20),
    ('sweatshirt', 'uconn quarterzip', 'M', 'sport-tek', 'navy blue', 3, 0),
    ('collared shirt', 'red and green flannel', 'M', 'st. johns bay', 'red / green', 3, 15),
    ('collared shirt', 'red and black flannel', 'L', 'american eagle', 'red', 3, 15),
    ('collared shirt', 'white button up', 'L', 'h&m', 'white', 2, 15),
    ('collared shirt', 'cream turtleneck', 'L', 'h&m', 'cream', 1, 15),
    ('collared shirt', 'soft button up', 'XL', 'ben sherman', 'white', 0, 0),
    ('collared shirt', 'gray button up', 'M', 'h&m', 'gray', 3, 15),
    ('collared shirt', 'old navy oxford green shirt', 'M', 'old navy', 'teal', 8, 0),
    ('collared shirt', 'red w/ white poka dots button up', 'M', 'h&m', 'red', 3, 15),
    ('collared shirt', 'green w/ blue poka dots button up', 'M', 'express', 'green', 3, 25),
    ('collared shirt', 'green polo shirt', 'L', 'banana republic', 'green', 0, 15),
    ('collared shirt', 'black polo shirt', 'L', 'banana republic', 'black', 0, 15),
    ('collared shirt', 'white polo shirt', 'L', 'banana republic', 'white', 0, 15),
    ('collared shirt', 'black button up', 'L', 'h&m', 'black', 2, 15),
    ('collared shirt', 'navy polo shirt', 'L', 'h&m', 'navy blue', 0, 15),
    ('collared shirt', 'salmon polo shirt', 'L', 'h&m', 'pink', 0, 15),
    ('collared shirt', 'lambent polo shirt', 'L', 'port authority', 'gray', 2, 0),
    ('collared shirt', 'lambent polo shirt', 'L', 'port authority', 'gray', 2, 0),
    ('collared shirt', 'uconn e&c services polo', 'M', 'devon & jones', 'navy blue', 3, 0),
    ('collared shirt', 'gift of life polo', 'M', 'port authority', 'blue', 3, 0),
    ('collared shirt', 'tolland soccer club polo', 'L', 'adidas', 'black', 2, 0),
    ('collared shirt', 'gray sweater', 'M', 'american eagle', 'gray', 3, 10),
    ('collared shirt', 'blue flannel', 'M', 'sonoma', 'blue', 7, 0),
    ('shorts', 'active shorts', 'L', 'soybu', 'gray', 0, 15),
    ('shorts', 'active shorts', 'L', 'soybu', 'black', 0, 15),
    ('shorts', 'active shorts', 'M', 'nike', 'navy blue', 8, 0),
    ('shorts', 'sweat shorts light blue', 'M', 'h&m', 'light blue', 1, 15),
    ('shorts', 'sweat shorts green', 'M', 'h&m', 'green', 1, 15),
    ('shorts', 'active shorts', 'M', 'icyzone', 'black', 2, 0),
    ('shorts', 'active shorts', 'M', 'nike', 'gray', 0, 10),
    ('shorts', 'pinstrip blue', '34', 'banana republic', 'blue', 1, 25),
    ('shorts', 'linen light blue', '34', 'saks fifth avenue', 'light blue', 0, 15),
    ('shorts', 'green khaki shorts', '34', 'banana republic', 'green', 1, 25),
    ('shorts', 'navy dress shorts', '33', 'h&m', 'navy blue', 1, 15),
    ('shorts', 'urban pipeline gray', '32', 'urban republic', 'gray', 6, 0),
    ('shorts', 'urban pipeline khaki', '32', 'urban republic', 'tan', 6, 0),
    ('shorts', 'urban pipeline light blue', '32', 'urban republic', 'blue', 6, 0),
    ('pants', 'loose fit jeans', '33x30', 'unlisted', 'blue', 2, 10),
    ('pants', 'gray hanes sweatpants', 'M', 'hanes', 'gray', 3, 0),
    ('pants', 'gray puma sweatpants', 'L', 'puma', 'gray', 1, 25),
    ('pants', 'black puma sweatpants', 'L', 'puma', 'black', 1, 25),
    ('pants', 'black fruit of the loom sweatpants', 'M', 'fruit of the loom', 'black', 3, 0),
    ('pants', 'blue fruit of the loom sweatpants', 'M', 'fruit of the loom', 'blue', 3, 0),
    ('pants', 'black jogger sweatpants', 'L', 'kirkland', 'black', 2, 0),
    ('pants', 'khaki chinos', '32x32', 'american eagle', 'tan', 3, 30),
    ('pants', 'green jeans', '33x30', 'banana republic', 'green', 1, 35),
    ('pants', 'uconn golf pants', '32x32', 'nike', 'tan', 2, 15),
    ('pants', 'jeans', '32x32', 'lucky brand', 'blue', 2, 10),
    ('pants', 'slim fit flex jeans', '32x32', 'american eagle', 'blue', 3, 10),
    ('pants', 'red chinos', '36x32', 'hollister', 'red', 2, 10),
    ('pants', 'gray dress pants', '34', 'h&m', 'gray', 2, 15),
    ('hat', 'dad hat nike golf', 'fits all', 'nike', 'gray', 3, 30),
    ('hat', 'uconn dad hat', 'fits all', 'nike', 'navy blue', 3, 30),
    ('hat', 'pga tour navy', 'fits all', 'pga', 'navy blue', 2, 0),
    ('hat', 'black titleist', 'fits all', 'titleist', 'black', 2, 0),
    ('hat', 'community servings', 'fits all', 'port authority', 'blue', 0, 0),
    ('jacket', 'bubble jacket', 'L', 'north face', 'black', 6, 0),
    ('jacket', 'green levis trucker', 'L', 'levi\'s', 'green', 3, 25),
    ('shoes', 'timbs', '11', 'timberland', 'tan', 4, 150),
    ('shoes', 'black dress shoes', '10.5', 'unlisted', 'black', 3, 70),
    ('shoes', 'steve madden dress shoes', '11', 'steve madden', 'black', 1, 0),
    ('shoes', 'navy and brown vans', '11', 'vans', 'blue', 3, 50),
    ('shoes', 'air force 1', '11', 'nike', 'white', 3, 35),
    ('shoes', 'tan dress shoes', '10', 'express', 'tan', 3, 12),
    ('shoes', 'white ck', '11', 'calvin klein', 'white', 3, 0),
    ('shoes', 'white and green sneakers', '10.5', 'h&m', 'white / green', 0, 20),
    ('shoes', 'adidas high tops', '11', 'adidas', 'gray', 7, 70),
    ('shoes', 'brown dress shoes', '11', 'apt 9', 'brown', 8, 0),
    ('shoes', 'gray / white adidas sneakers', '11', 'adidas', 'gray', 7, 0),
    ('shoes', 'running shoes', '11', 'brooks', 'purple / gray', 2, 140)
]